Vagrant.configure("2") do |config|
  config.vm.provision "shell", inline: "echo Hello"
  config.vm.network "private_network", type: "dhcp"

  config.vm.provision "shell", inline: "apt-get update > /dev/null"

  config.vm.define "web" do |web|
    web.vm.box = "hashicorp/precise32"

    #provision
    web.vm.provision "shell", inline: "apt-get -y install apache2"

    #network
    web.vm.network "forwarded_port", guest: 80, host: 8080
    #web.vm.network "private_network", ip: "192.168.50.4"
  end

  config.vm.define "db" do |db|
    db.vm.box = "hashicorp/precise32"

    #provision
    #db.vm.provision "shell", inline: "apt-get -y install mongodb"

    #network
    #db.vm.network "private_network", ip: "192.168.50.5"
  end
end