Vagrant.configure("2") do |config|
  config.vm.provision "shell", inline: "echo Hello"
  config.vm.network "private_network", type: "dhcp"

  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--natnet1", '192.168/16']
  end


  config.vm.provision "shell", run: 'once', inline: <<-EOF
    rm -f /etc/apt/apt.conf.d/95proxies
    echo 'Acquire::http::proxy "http://proxy.non.3dart.com:3128";' >> /etc/apt/apt.conf.d/95proxies
    echo 'Acquire::ftp::proxy "ftp://proxy.non.3dart.com:3128";' >> /etc/apt/apt.conf.d/95proxies
    echo 'Acquire::https::proxy "https://proxy.non.3dart.com:3128";' >> /etc/apt/apt.conf.d/95proxies
  EOF

  config.vm.provision "shell", run: 'always', inline: "apt-get update"

  config.vm.define "web" do |web|
    web.vm.box = "hashicorp/precise32"

    #provision
    web.vm.provision "shell", inline: "apt-get -y install apache2"

    #network
    web.vm.network "forwarded_port", guest: 80, host: 8080
    #web.vm.network "private_network", ip: "192.168.50.4"
  end

  config.vm.define "db" do |db|
    db.vm.box = "hashicorp/precise32"

    #provision
    #db.vm.provision "shell", inline: "apt-get -y install mongodb"

    #network
    #db.vm.network "private_network", ip: "192.168.50.5"
  end
end
